{
 "title": "Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Questions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Answers correctness distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(quiz_correct_answers)", "legendFormat": "Correct" },
    { "expr": "sum(quiz_incorrect_answers)", "legendFormat": "Incorrect" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(quiz_correct_answers)", "legendFormat": "Correct" },
    { "expr": "sum(quiz_incorrect_answers)", "legendFormat": "Incorrect" }
   ]
  },
  {
   "title": "Average time per question",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(quiz_time_answering_seconds_sum[1y])) / (sum(rate(quiz_time_answering_seconds_count[1y])))",
     "legendFormat": "Average time (seconds)"
    }
   ]
  },
  {
   "title": "Top 5 hardest questions",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "quiz_incorrect_answers{question_index!=\"23\", question_index!=\"644\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Testing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tests_passed", "legendFormat": "Pass" },
    { "expr": "tests_failed", "legendFormat": "Fail" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tests_passed", "legendFormat": "Pass" },
    { "expr": "tests_failed", "legendFormat": "Fail" }
   ]
  },
  {
   "title": "Recent fails",
   "type": "logs",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"test-log\", severity=\"critical\"}"
    }
   ]
  },
  {
   "title": "Test time / workers",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (n_workers) (\r\n  tests_total_time_sum / tests_total_time_count\r\n)\r\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Difference on load",
   "type": "stat",
   "gridPos": { "h": 12, "w": 2, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  avg(tests_total_time_sum{n_workers=\"4\"}) / avg(tests_total_time_count{n_workers=\"4\"})\r\n    -\r\n  avg(tests_total_time_sum{n_workers=\"3\"}) / avg(tests_total_time_count{n_workers=\"3\"})\r\n)\r\n/\r\n(\r\n  avg(tests_total_time_sum{n_workers=\"3\"}) / avg(tests_total_time_count{n_workers=\"3\"})\r\n)\r\n* 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Test time / workers",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (n_workers) (\r\n  tests_total_time_sum / tests_total_time_count\r\n)\r\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}